import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import ReduxProvider from "./ReduxProvider";
import NavBar from "./NavBar";
import ThemeManager from './ThemeManager'


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        
        className={`${inter.variable} ${robotoMono.variable} antialiased`}
      >
        <ReduxProvider>
          <NavBar />
          {children}
          <ThemeManager />
        </ReduxProvider>
      </body>
    </html>
  );
}
